#!/bin/bash
OE_USER="odoo"
OE_HOME="/$OE_USER"
OE_HOME_EXT="/$OE_USER/$OE_USER-server"
cd HOME_EXT
username="$(git config --global user.name)"
email="$(git config --global user.email)"
if [[ ${#username} -gt 0 || ${#email} -gt 0 ]]
then
  echo "We can do a git pull - git user configged."
  #git pull origin master
else
  echo "We can not update the Odoo code base - no git user configged"
fi
  echo "------Finished the script------"
